// journals.js
const HK_JOURNALS = [
  "Crawlid",
  "Vengefly",
  "Vengefly King",
  "Gruzzer",
  "Gruz Mother",
  "Tiktik",
  "Aspid Hunter",
  "Aspid Mother",
  "Aspid Hatchling",
  "Goam",
  "Wandering Husk",
  "Husk Hornhead",
  "Leaping Husk",
  "Husk Bully",
  "Husk Warrior",
  "Husk Guard",
  "Entombed Husk",
  "False Knight",
  "Maggot",
  "Menderbug",
  "Lifeseed",
  "Baldur",
  "Elder Baldur",
  "Mosscreep",
  "Mossfly",
  "Mosskin",
  "Volatile Mosskin",
  "Fool Eater",
  "Squit",
  "Obble",
  "Gulka",
  "Maskfly",
  "Moss Charger",
  "Massive Moss Charger",
  "Moss Knight",
  "Mossy Vagabond",
  "Durandoo",
  "Duranda",
  "Aluba",
  "Charged Lumafly",
  "Uoma",
  "Ooma",
  "Uumuu",
  "Ambloom",
  "Fungling",
  "Fungoon",
  "Sporg",
  "Fungified Husk",
  "Shrumeling",
  "Shrumal Warrior",
  "Shrumal Ogre",
  "Mantis Youth",
  "Mantis Warrior",
  "Mantis Lords",
  "Husk Sentry",
  "Heavy Sentry",
  "Winged Sentry",
  "Lance Sentry",
  "Mistake",
  "Folly",
  "Soul Twister",
  "Soul Warrior",
  "Soul Master",
  "Husk Dandy",
  "Cowardly Husk",
  "Gluttonous Husk",
  "Gorgeous Husk",
  "Great Husk Sentry",
  "Watcher Knight",
  "The Collector",
  "Belfly",
  "Pilflip",
  "Hwurmp",
  "Bluggsac",
  "Dung Defender",
  "Flukefey",
  "Flukemon",
  "Flukemunga",
  "Flukemarm",
  "Shardmite",
  "Glimback",
  "Crystal Hunter",
  "Crystal Crawler",
  "Husk Miner",
  "Crystallised Husk",
  "Crystal Guardian",
  "Furious Vengefly",
  "Volatile Gruzzer",
  "Violent Husk",
  "Slobbering Husk",
  "Dirtcarver",
  "Carver Hatcher",
  "Garpede",
  "Corpse Creeper",
  "Deepling",
  "Deephunter",
  "Little Weaver",
  "Stalking Devout",
  "Nosk",
  "Shadow Creeper",
  "Lesser Mawlek",
  "Mawlurk",
  "Brooding Mawlek",
  "Lightseed",
  "Infected Balloon",
  "Broken Vessel",
  "Boofly",
  "Primal Aspid",
  "Hopper",
  "Great Hopper",
  "Grub Mimic",
  "Hiveling",
  "Hive Soldier",
  "Hive Guardian",
  "Husk Hive",
  "Hive Knight",
  "Spiny Husk",
  "Loodle",
  "Mantis Petra",
  "Mantis Traitor",
  "Traitor Lord",
  "Sharp Baldur",
  "Armoured Squit",
  "Battle Obble",
  "Oblobble",
  "Shielded Fool",
  "Sturdy Fool",
  "Winged Fool",
  "Heavy Fool",
  "Death Loodle",
  "Volt Twister",
  "God Tamer",
  "Pale Lurker",
  "Xero",
  "Gorb",
  "Elder Hu",
  "Marmu",
  "No Eyes",
  "Galien",
  "Markoth",
  "Grimmkin Novice",
  "Grimmkin Master",
  "Grimmkin Nightmare",
  "Grimm",
  "Nightmare King",
  "Wingmould",
  "Royal Retainer",
  "Kingsmould",
  "Sibling",
  "Void Tendrils",
  "Hornet",
  "Shade"
];
